---
title: "Chaff"
author: "Monica"
date: "04/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE,
                      message = FALSE, 
                      fig.retina = 3)
```

## Introduction

```{r packages}
library(tidyverse)
library(tidyr)
library(dplyr)
```

## Methods

#Import the data into R Markdown

```{r packages}
chaff<-read.table("./chaff.txt", header = TRUE)
```

#Tidy the data

```{r packages}
# Rearrange the data so that the columns are sex and mass rather than males and females

chaff2<-chaff%>%
  pivot_longer(names_to = "sex",
               values_to = "mass",
               cols= (everything()))

chaff2

```

#Calculating the SS(x) for all of the data

```{r packages}
sum_sq <- function(df, measure) {
  df %>% summarise(ss = sum(({{measure}} - mean({{measure}}))^2))
}

sum_sq (chaff2, mass)
```

#Calculating the SS(x) for males and females

```{r packages}
sum_sq <- function(df, measure, group) {
  df %>% group_by({{ group }}) %>% 
    summarise(ss = sum(({{measure}} - mean({{measure}}))^2))
}

sum_sq(chaff2, mass, sex)
```

#Summarise data by sex

This includes mean, standard deviation, sample size and standard error

```{r packages}

standard_error <- function(x) sd(x) / sqrt(length(x))

chaff_summary <- chaff2 %>%
  group_by(sex) %>%
  summarise(mean_mass = mean(mass),
            n= length(mass),
            standard_deviation = sd(mass),
            standard_error(mass))

chaff_summary
```

#Create a function that summarises

```{r packages}

standard_error <- function(x) sd(x) / sqrt(length(x))

data_summary <- function(df, measure, group) {
  df %>% group_by({{ group }}) %>% 
    summarise(ss = sum(({{measure}} - mean({{measure}}))^2), 
            mean = mean({{measure}}),
            n= length({{measure}}),
            standard_deviation = sd({{measure}}),
            standard_error= sd({{measure}}) / sqrt(length({{measure}})))
}

data_summary(chaff2, mass, sex)
```

## Results



## Discussion